name: Gordon
favicon: null
layout_spectrum: 0.5229293517768383
typography_spectrum: 0.3260244927369058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.27161544980481267
  lightness: 0.1539044170640409
  saturation: 0.8943648519925773
  rhythmicContrast: 0.4144897705409676
purpose: []
